project:
  type: website

website:
  title: "crfmr"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Material
        menu: 
          - installing.qmd
          - intro.qmd
          - visualization1.qmd
          - import.qmd
          - resources.qmd
          - data.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

