project:
  type: website
  render:
    - "*.qmd"
    - "*.Rmd"
    - "!ignored-dir/"
    - "!background/"

website:
  title: "crfmr"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Material
        menu: 
          - import.qmd
    right: 
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/fishvice/crfmr
          - text: Report a Bug
            url:  https://github.com/fishvice/crfmr/issues
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

