project:
  type: website

website:
  title: "crfmr"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Material
        menu: 
          - intro.qmd
          - ggplot1.qmd
          - transformation1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

