---
title: "Report of the ..."
---

# Summary

The training course in the ... took place ... Hotel, in Barbados from ... to .... The number of participants was XX, coming from YY different institudes and ZZ countries.

The objective of the course was to provide participants with a solid foundation in efficient use of the R environment using various typical and familiar fisheries datasets as case examples. Emphasis was put on efficient data munging, data visualization using literate programming starting with "raw" data (individual stations, individual observation) and culminating with deliverance of publishable output produced from a single coded document file.

From the conception of the course through deliverance, all course material were developed and delivered using non-proprietary free software and made available as open source (https://github.com/fishvice/crfmr). A course webpage (https://heima.hafro.is/~einarhj/crfmr) based on the source code was generated and used throughout the course.

# Background

## Context

The R language is becoming the _Lingua franca_ both in data science in general as well as within the ICES community. Recent advancements within R have resulted in that R can no longer be considered as a specific statistical programming language but as a general scientific working environment. This broader environment has resulted in the R has become a natural component of reproducible data analysis and document writing.

Various R packages (e.g. FLR, DATRAS, MSY, SURBAR, VMStools) have often been the backbone of ICES training course and/or workshops. These packages as well as courses are geared towards solving specific pending tasks that tend to come with requirements that the participants are reasonable proficient in basic R and that the input data are correctly formatted and available. Any of these requirements have been seen to pose problems.

The course is aimed at covering the fundamental/generic basis of the grammar of data and graphics as well reproducible document writing where R is used as the sole working medium. Recent developments in the R community that are of interest to fisheries science will also be described.

## Objective

The objective of the course is to provide participants with a solid foundation in efficient use of the R environment using various typical and familiar fisheries data sets (landings data, catch data, survey data and tagging data) as case examples. Emphasis will be put on data munging and literate programming starting with "raw" data (individual stations, individual fish measurements, ...) and culminating with deliverance of publishable output produced from a single coded document file.

By the end of the course, the participants:

* Will be able to import data from multitude of sources computer (i.e. own text files, excel, access, sql databases) and via the web.
* Will be able to clean, manipulate, explore, summarize and graph data. This includes being able to:
    - Apply best practices in data preparation
    - Present results graphically, highlighting significant results
    - Merge, slice and dice various datasets
* Will be able to apply the principle of reproducible analysis and report writing from A through Z which are then deliverable through any of the current three common deliverable formats: .html, .pdf and .docx.
* Will be able to produce own functions and understand the principles of creating R packages and social version control coding (through www.github.com).

## Level

The course is targeted at fisheries scientist with already have some basic experience in R but are yet not proficient enough to write fluently code for data manipulation, exploration and writing own functions. We believe that some part of the course would also be beneficial to those that are currently productively using R in fisheries science but may along the way have skipped some of the basics and/or are unaware of recent advancements in the R environment when it comes to efficient data handling and processing.

# Course Programme, Product, Deliverance and Instructors

The training course in the R environment took place at ICES Headquarters, in Copenhagen, Denmark from 21. August to 28. August 2017. The number of participants was 17, coming from 13 different institudes.

## Programme

The schedule was as follows:

### 2023-06-09 10:30-12:30 (Online)

-   [Introduction](intro.qmd)

### 2023-06-12 10:30-12:30 (Online)

-   [Visualization 1](visualization1.qmd)

### 2023-06-14 10:30-12:30 (Online)

-   [Transformation 1](transformation1.qmd)

### 2023-06-16 10:30-12:30 (Online)

-   [Statistical Modelling with R](statistics-with-r.qmd)

### Wednesday, 2023-06-21 09:00-17:00

-   08:30 - 10:00: Opening
-   10:00 - 10:30: [Import](import.qmd) (EH)
-   10:30 - 10:45: Break
-   10:45 - 12:00: Import - continued (EH)
-   12:00 - 13:00: Lunch
-   13:00 - 14:00: [Transformation 2](transformation2.qmd) (EH)
-   14:00 - 14:45: [Tidy datasets](tidy.qmd) (EH)
-   14:45 - 15:00: Break
-   15:00 - 17:00: General Q&A, participant work


### Thursday, 2023-06-22 09:00-17:00

-   09:00 - 10:30: [EDA](eda1.qmd) (EH)
-   10:30 - 10:45: Break
-   10:45 - 11:30. EDA - continued (EH)
-   11:15 - 12:00: [Estimating catch and effort](CPUE_lecture.qmd) (WS)
-   12:00 - 13:00: Lunch
-   13:00 - 14:45: [Generalized linear regression - - CPUE standardization](CPUE_demo2.qmd)  (WS)
-   14:45 - 15:00: Break
-   15:00 - 16:30: [The Fisheries Manager](https://fishtech.is/) (VH)
-   16:30 - 17:00: General Q&A, participant work

### Friday, 2023-06-23 09:00-17:00

-   09:00 - 09:45: [The fundamental fisheries equations](https://heima.hafro.is/~einarhj/CFB) (EH)
-   09:45 - 10:30: [Stock production models](https://heima.hafro.is/~einarhj/crfmr/aux/surplus-production_models_GRO-ftp.pptx) (PP)
-   10:30 - 10:45: Break
-   10:45 - 12:00: [CMSY++](https://heima.hafro.is/~einarhj/crfmr/aux/CMSY++.pptx) (PP)
-   12:00 - 13:00: Lunch
-   13:00 - 14:45: CMSY++ practial (PP)
-   14:45 - 15:00: Break
-   15:00 - 16:00: CMSY++ practial (PP)
-   16:00 - 18:00: Subgroup: [The Fisheries Manager](https://fishtech.is/) (VH)

### Saturday, 2023-06-24 09:00-13:00

-   09:00 - 09:45: CMSY++ (PP) - continued
-   09:45 - 10:30: [Using R to connect to an MS Access database](https://heima.hafro.is/~einarhj/crfmr/aux/connecting-r-to-ms-access-database.html) (DT)
-   10:30 - 10:45: Break
-   10:45 - 11:30: [Project setup](project_setup.qmd) (KH)
                   [R markdown](rmarkdown.qmd) (KH)
-   11:30 - 13:00: Fellows presentations, coffee inbetween's
-   14:00 - 16:00: Catch-up: one-on-one sessions for those that are lost - "conference room"

### Sunday, 2023-06-24

-   09:00 - 12:00: Instructors present in the "conference room"
-   15:00 - Inf: Instructors available per prior personal request

### Monday, 2023-06-26 09:00-17:00

-   09:00 - 10:00: Presentations
-   10:00 - 10:30: General Q&A, participant work
-   10:30 - 10:45: Break
-   10:45 - 11:15: General Q&A, participant work
-   11:15 - 12:00: Creating maps in R (MF) ... document pending
-   12:00 - 13:00: Lunch
-   13:00 - 14:45: Presentations
-   14:45 - 15:00: Break
-   15:00 - 16:00: Presentations
-   16:00 - 17:00: [Leaflet-maps](https://heima.hafro.is/~einarhj/leaflet/leaflet.html) (EH)

### Tuesday, 2023-06-27 09:00-17:00

-   09:00 - 10:30: [Length based spawning potential ratio](https://heima.hafro.is/~einarhj/crfmr/aux/LB-SPR-GRO-FTP-27-06-23.pptx) (PP)
    - [shiny link](http://barefootecologist.com.au/lbspr) (PP)
    - [LBSPR package webpage](http://adrianhordyk.github.io/LBSPR/articles/LBSPR.html) (PP)
-   10:30 - 10:45: Break
-   10:45 - 11:30: LBSP - continued (PP)
-   11:30 - 12:00: Ad-hoc issues
-   12:00 - 13:00: Lunch
-   13:00 - 14:00: Our afterlife (DT)
-   14:00 - 15:00: Wrap-up
-   15:00 - 16:00: Meeting with stakeholders
-   16:00 - 16:15: Closing

## Course products

From the conception of the course through deliverance, all course material were developed and delivered using non-proprietary free software. In that spirit all the material was also made available as open source on a github repository (https://github.com/fishvice/tcrenv2017). The repository contains all source documents (lectures in the form of .Rmd and/or .Rnw). A webpage (http://www.hafro.is/~einarhj/education/tcrenv2017) based on that material was also generated and used in delivery of the course.

The above product allows anybody interest to make a full copy of the course, either as a compiled zip-document (https://github.com/fishvice/tcrenv2017/archive/master.zip) or by simply typing in a terminal window on computers where the git program has been installed:
```
git clone https://github.com/fishvice/tcrenv2017.git
```
The source code for course is shared via the creative commons licence, allowing anybody to reuse any or all of the material produced for the course. 

## Deliverables

The deliverance of the course deviated somewhat from the planned schedule because mainly because the coverage of each topic, including practical assignments took longer than anticipated. This resulted in that some of the topics (mainly function, packages and social coding) were only covered with brief lectures without participants hands on training.

Each day started with a short discussion of the topics/assignments covered the previous day. During the deliverance emphasis was put on cooperative work and code sharing (including difficulties/stumbling blocks) among participants. Once the basic elements had been introduced within the first three days course participants were encouraged to work with their own data and problems, the instructors being at hand to suggest solutions when issues arouse. The participants data and issues tackled were quite diverse and included the automatic generation of cruise reports, animations of temporal changes in species distribution and interactions to big data sets located in a remote SQL database.   

## Lecturers

* Bjarki Þór Elvarsson, Marine and Freshwater Research Institute, Iceland
    - Bjarki is a statistician at the Demersal Division of the Marine and Freshwater Research Institute, Reykjavík Iceland. His main research focuses on statistical methods related to stock assessment models. He has been a member of the Icelandic delegation to the scientific council of International whaling commission since 2010 and participated in various ICES working group meetings since 2013. R has been in his main working environment since 2004. 
* Einar Hjörleifsson, Marine and Freshwater Research Institute, Iceland
    - Einar is a fisheries scientist at the Data Division of the Marine and Freshwater Research Institute, Reykjavík Iceland. He has been involved in various ICES works since 1996 that spans the whole spectrum from ACFM membership up to working group chairing and participation. He has also been involved in the United Nation University Fisheries Training Program teaching stock assessment. R has been his primary working environment since 2009.

# Recommendation


In the waning hour of the course a discussion focusing on the documentation, deliverance and what may have been handled better by the instructors. The main comments on the latter were:

* Provide guidance on naming of objects.
* Allow more time in lecture on the assigned exercises.
* Provide a better deliverance of the solution to the exercises (now stored within the Rmd-source documents).
* The prearranged projects be categorized with respect to the issues they address. 
* Set the frame structure in RStudio up such that the source code is on the left and the console is on the right (instead of below).

# Annex 1: List of participants

```{r}
readr::read_csv("ignored-dir/background/participants.csv") |> 
  dplyr::select(name, country, pos, funding)
```


# Annex 2: Results of course evaluation questionnaire

...